### PR TITLE
Fetch server_id from server_info call

### LINKED ISSUE #147: KeyError: 'server_id' during startup of Unifi Protect
After restart of Home Assistant, some of the entities (Switch, Sensor and binary_sensor) sometimes returns a *KeyError: 'server_id'* like the below. 

```log
2020-11-29 08:03:53 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up unifiprotect platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/unifiprotect/sensor.py", line 32, in async_setup_entry
sensors.append(UnifiProtectSensor(upv_object, protect_data, camera, sensor))
File "/config/custom_components/unifiprotect/sensor.py", line 45, in __init__
super().__init__(upv_object, protect_data, camera_id, sensor)
File "/config/custom_components/unifiprotect/entity.py", line 23, in __init__
self._server_id = self._camera_data["server_id"]
KeyError: 'server_id'
```

### PR DESCRIPTION
**Pull request by bdraco**
Various cleanups to existing platforms

Fixes #147

### CODE REVIEW

**Comment by briis** [comment]
Thanks Nick.

**Comment by briis** [comment]
I just tested it, and I get a camera.none device. Can you see why?

**Comment by bdraco** [comment]
> I just tested it, and I get a camera.none device. Can you see why?
> 
> 
> 
> EDIT: I get all the cameras I expected + 1 one extra called camera.none

I was getting that before the change. I'll look into it later today.

**Comment by bdraco** [comment]
The 1.17+ firmware lists all the non-adopted camera in the api

```
              'isAdopted': False,                                                 
              'isAdoptedByOther': True,                                       
              'isAdopting': False,        
```

**Comment by bdraco** [comment]
Fixed here https://github.com/briis/pyunifiprotect/pull/17

**Pull request merged**
