### PR TITLE
Direct UnifiOS support

### PR DESCRIPTION
**Pull request by msvinth**
This is a DRAFT PR with a fix for #21 
This works with my UDM Pro without the use of the Proxy, ie the config is:

```
unifiprotect:
    host: 192.168.1.1
    port: 443
    username: !secret unifiprotect_user
    password: !secret unifiprotect_password
```
@briis I don't have the a CloudKey any more, could you please test if these changes works against the CouldKey?

### CODE REVIEW

**Comment by briis** [comment]
Hi @msvinth 
Just testet this, and it WORKS also on a CloudKey+. Thank you so much for doing this, I believe you are making a lot of UDMP people happy. 
I'll just test a bit more, and if nothing shows up, I will merge the PR and release a new version.

**Comment by msvinth** [comment]
> Hi @msvinth
> Just testet this, and it WORKS also on a CloudKey+. Thank you so much for doing this, I believe you are making a lot of UDMP people happy.
> I'll just test a bit more, and if nothing shows up, I will merge the PR and release a new version.

Let me just clean up the PR a bit and push it again to you.

**Comment by briis** [comment]
Deal. Let me know when you are happy with the clean-up.

**Comment by briis** [comment]
Hi again,
I made a rookie mistake and copied the wrong files (The original files). When adding your changes I do get errors, and none of the components are loading. Here is the output from the DEBUG log:
````
2020-05-05 09:59:24 DEBUG (MainThread) [custom_components.unifiprotect] Connected to Unifi Protect Platform
2020-05-05 09:59:24 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] https://192.168.1.3:7443
2020-05-05 09:59:24 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] 200 text/html <ClientResponse(https://192.168.1.3:7443) [200 OK]>
<CIMultiDictProxy('X-Powered-By': 'Express', 'Vary': 'Origin', 'Access-Control-Allow-Credentials': 'true', 'Accept-Ranges': 'bytes', 'Cache-Control': 'public, max-age=0', 'Last-Modified': 'Thu, 30 Apr 2020 10:18:33 GMT', 'Etag': 'W/"281-171ca9854a8"', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '641', 'Date': 'Tue, 05 May 2020 07:59:24 GMT', 'Connection': 'keep-alive')>

2020-05-05 09:59:24 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] https://192.168.1.3:7443/api/auth/login
2020-05-05 09:59:24 ERROR (MainThread) [custom_components.unifiprotect] Unexpected error fetching unifiprotect data: Cannot serialize non-str key None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 136, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 74, in update
    await self.login()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 104, in login
    await self.request("post", url=url, json=auth)
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 416, in request
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 502, in _request
    resp = await req.send(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 629, in send
    await writer.write_headers(status_line, self.headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 111, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp\_http_writer.pyx", line 138, in aiohttp._http_writer._serialize_headers
  File "aiohttp\_http_writer.pyx", line 110, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None
2020-05-05 09:59:24 DEBUG (MainThread) [custom_components.unifiprotect] Finished fetching unifiprotect data in 0.647 seconds
````

**Comment by msvinth** [comment]
> Hi again,
> I made a rookie mistake and copied the wrong files (The original files). When adding your changes I do get errors, and none of the components are loading. Here is the output from the DEBUG log:
> 
> ```
> 2020-05-05 09:59:24 DEBUG (MainThread) [custom_components.unifiprotect] Connected to Unifi Protect Platform
> 2020-05-05 09:59:24 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] https://192.168.1.3:7443
> 2020-05-05 09:59:24 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] 200 text/html <ClientResponse(https://192.168.1.3:7443) [200 OK]>
> <CIMultiDictProxy('X-Powered-By': 'Express', 'Vary': 'Origin', 'Access-Control-Allow-Credentials': 'true', 'Accept-Ranges': 'bytes', 'Cache-Control': 'public, max-age=0', 'Last-Modified': 'Thu, 30 Apr 2020 10:18:33 GMT', 'Etag': 'W/"281-171ca9854a8"', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '641', 'Date': 'Tue, 05 May 2020 07:59:24 GMT', 'Connection': 'keep-alive')>
> 
> 2020-05-05 09:59:24 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] https://192.168.1.3:7443/api/auth/login
> 2020-05-05 09:59:24 ERROR (MainThread) [custom_components.unifiprotect] Unexpected error fetching unifiprotect data: Cannot serialize non-str key None
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 136, in async_refresh
>     self.data = await self._async_update_data()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _async_update_data
>     return await self.update_method()
>   File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 74, in update
>     await self.login()
>   File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 104, in login
>     await self.request("post", url=url, json=auth)
>   File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 416, in request
>     **kwargs,
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
>     self._resp = await self._coro
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 502, in _request
>     resp = await req.send(conn)
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 629, in send
>     await writer.write_headers(status_line, self.headers)
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 111, in write_headers
>     buf = _serialize_headers(status_line, headers)
>   File "aiohttp\_http_writer.pyx", line 138, in aiohttp._http_writer._serialize_headers
>   File "aiohttp\_http_writer.pyx", line 110, in aiohttp._http_writer.to_str
> TypeError: Cannot serialize non-str key None
> 2020-05-05 09:59:24 DEBUG (MainThread) [custom_components.unifiprotect] Finished fetching unifiprotect data in 0.647 seconds
> ```

I will take a look

**Comment by msvinth** [comment]
Please check if it works now

**Comment by briis** [comment]
Different error. Now I cannot login. Here is the error:
````
2020-05-05 10:26:18 DEBUG (MainThread) [custom_components.unifiprotect] Connected to Unifi Protect Platform
2020-05-05 10:26:18 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] https://192.168.1.3:7443
2020-05-05 10:26:18 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] 200 text/html <ClientResponse(https://192.168.1.3:7443) [200 OK]>
<CIMultiDictProxy('X-Powered-By': 'Express', 'Vary': 'Origin', 'Access-Control-Allow-Credentials': 'true', 'Accept-Ranges': 'bytes', 'Cache-Control': 'public, max-age=0', 'Last-Modified': 'Thu, 30 Apr 2020 10:18:33 GMT', 'Etag': 'W/"281-171ca9854a8"', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '641', 'Date': 'Tue, 05 May 2020 08:26:18 GMT', 'Connection': 'keep-alive')>

2020-05-05 10:26:18 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] https://192.168.1.3:7443/api/login
2020-05-05 10:26:18 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] 401 application/json <ClientResponse(https://192.168.1.3:7443/api/login) [401 Unauthorized]>
<CIMultiDictProxy('X-Powered-By': 'Express', 'Vary': 'Origin', 'Access-Control-Allow-Credentials': 'true', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '53', 'Etag': 'W/"35-hAV5CwI1DJGe6lPjJa4GW8xYOIs"', 'Date': 'Tue, 05 May 2020 08:26:18 GMT', 'Connection': 'keep-alive')>

2020-05-05 10:26:18 ERROR (MainThread) [custom_components.unifiprotect] Unexpected error fetching unifiprotect data: Unifi Protect reported authorization failure on request: https://192.168.1.3:7443/api/login received 401
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 136, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 73, in update
    await self.login()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 102, in login
    await self.request("post", url=url, json=auth)
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 386, in request
    f"Unifi Protect reported authorization failure on request: {url} received {res.status}"
custom_components.unifiprotect.unifi_protect_server.NotAuthorized: Unifi Protect reported authorization failure on request: https://192.168.1.3:7443/api/login received 401
2020-05-05 10:26:18 DEBUG (MainThread) [custom_components.unifiprotect] Finished fetching unifiprotect data in 0.585 seconds
````

**Comment by msvinth** [comment]
Hopefully a little bit further now. I guess this is going to be a bit of trial and error.

**Comment by briis** [comment]
Yes we got further now. Still errors, but we are moving in the right direction. I know the frustrating feeling of not having the HW myself. It could be fixed in no time. 
Anyway, now I am logged in, but getting authentication errors when retrieving cameras:

````
2020-05-05 10:43:02 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] 200 text/html <ClientResponse(https://192.168.1.3:7443) [200 OK]>
<CIMultiDictProxy('X-Powered-By': 'Express', 'Vary': 'Origin', 'Access-Control-Allow-Credentials': 'true', 'Accept-Ranges': 'bytes', 'Cache-Control': 'public, max-age=0', 'Last-Modified': 'Thu, 30 Apr 2020 10:18:33 GMT', 'Etag': 'W/"281-171ca9854a8"', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '641', 'Date': 'Tue, 05 May 2020 08:43:02 GMT', 'Connection': 'keep-alive')>

2020-05-05 10:43:02 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] https://192.168.1.3:7443/api/auth
2020-05-05 10:43:02 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] 200 application/json <ClientResponse(https://192.168.1.3:7443/api/auth) [200 OK]>
<CIMultiDictProxy('X-Powered-By': 'Express', 'Vary': 'Origin', 'Access-Control-Allow-Credentials': 'true', 'Authorization': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMjM2ODg0MDBmYTY3MDNlNzAwMDRlMCIsImlhdCI6MTU4ODY2ODE4Mn0.sAlYhBygtWBMxmBJMU3UNoAifmJjRsY7ywy5Etga4uA', 'Access-Control-Expose-Headers': 'Authorization', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '1245', 'Etag': 'W/"4dd-lmyS6nkdEmgxT7SGdWUAcZepRIE"', 'Date': 'Tue, 05 May 2020 08:43:02 GMT', 'Connection': 'keep-alive')>

2020-05-05 10:43:02 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] Unifi OS: False
2020-05-05 10:43:02 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] Authenticated: True
2020-05-05 10:43:03 ERROR (MainThread) [custom_components.unifiprotect] Unexpected error fetching unifiprotect data: Fetching Camera List failed: 401 - Reason: Unauthorized
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 136, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 78, in update
    await self._get_camera_list()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 199, in _get_camera_list
    f"Fetching Camera List failed: {response.status} - Reason: {response.reason}"
custom_components.unifiprotect.unifi_protect_server.NvrError: Fetching Camera List failed: 401 - Reason: Unauthorized
2020-05-05 10:43:03 DEBUG (MainThread) [custom_components.unifiprotect] Finished fetching unifiprotect data in 1.417 seconds
````

**Comment by msvinth** [comment]
Another attempt

**Comment by briis** [comment]
New error:
````
2020-05-05 11:06:55 DEBUG (MainThread) [custom_components.unifiprotect] Connected to Unifi Protect Platform
2020-05-05 11:06:55 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] https://192.168.1.3:7443
2020-05-05 11:06:56 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] 200 text/html <ClientResponse(https://192.168.1.3:7443) [200 OK]>
<CIMultiDictProxy('X-Powered-By': 'Express', 'Vary': 'Origin', 'Access-Control-Allow-Credentials': 'true', 'Accept-Ranges': 'bytes', 'Cache-Control': 'public, max-age=0', 'Last-Modified': 'Thu, 30 Apr 2020 10:18:33 GMT', 'Etag': 'W/"281-171ca9854a8"', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '641', 'Date': 'Tue, 05 May 2020 09:06:56 GMT', 'Connection': 'keep-alive')>

2020-05-05 11:06:56 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] https://192.168.1.3:7443/api/auth
2020-05-05 11:06:57 DEBUG (MainThread) [custom_components.unifiprotect.unifi_protect_server] 200 application/json <ClientResponse(https://192.168.1.3:7443/api/auth) [200 OK]>
<CIMultiDictProxy('X-Powered-By': 'Express', 'Vary': 'Origin', 'Access-Control-Allow-Credentials': 'true', 'Authorization': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMjM2ODg0MDBmYTY3MDNlNzAwMDRlMCIsImlhdCI6MTU4ODY2OTYxNn0.sF_gjufgw-f0Njk12T-AYS7-r4NSWdHIdsXBq4Nai_I', 'Access-Control-Expose-Headers': 'Authorization', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '1245', 'Etag': 'W/"4dd-lmyS6nkdEmgxT7SGdWUAcZepRIE"', 'Date': 'Tue, 05 May 2020 09:06:56 GMT', 'Connection': 'keep-alive')>

2020-05-05 11:06:57 ERROR (MainThread) [custom_components.unifiprotect] Unexpected error fetching unifiprotect data: 'dict' object has no attribute 'headers'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 136, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 124, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 73, in update
    await self.login()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 105, in login
    "Authorization": f"Bearer {response.headers.get('Authorization')}"
AttributeError: 'dict' object has no attribute 'headers'
2020-05-05 11:06:57 DEBUG (MainThread) [custom_components.unifiprotect] Finished fetching unifiprotect data in 1.522 seconds
````

**Comment by msvinth** [comment]
Another attempt

**Comment by briis** [comment]
YES, now it works. I don't get any errors in the Log, and quick testing shows that everything works. I will test some more and post the results here. 
I assume that the UDMP part still works also?

**Comment by msvinth** [comment]
Yes UDMP part still works

**Comment by briis** [comment]
Everything is still running here, so unless you have more changes, I will merge the PR into the master and make a new release.

**Comment by msvinth** [comment]
I don't have more changes. 
UDMP is also running fine here, so it should be good to go.

**Comment by briis** [comment]
Last thing: I want to give you the credit on the Home Assistant forum, what is your forum username?

**Comment by msvinth** [comment]
My forum name is: Msv1

And thanks to you @briis for making this integration!

**Comment by msvinth** [comment]
Btw you should highlight that people using the proxy, should update the config to point directly to the UDMP and set port to 443 e.g.

```
unifiprotect:
    host: 192.168.1.1
    port: 443
    username: !secret unifiprotect_user
    password: !secret unifiprotect_password
```

**Comment by briis** [comment]
Thank you - I just need to update the documentation, then I am ready to go. Hope you can support if users find problems with the UDMP part.

**Pull request merged**
