### PR TITLE
Switch to a dataclass for config entry data

### PR DESCRIPTION
**Pull request by bdraco**

### CODE REVIEW

**Comment by briis** [comment]
Is this in preparation for switching to the `ProtectApiClient` from `UpvServer`?

**Comment by bdraco** [comment]
Nope, its just a cleanup so its easier to type the data stored in `hass.data` later.

**Comment by bdraco** [comment]
I still need to find some type to finish up the cleanups to `select.py` and implement a reauth flow. Once thats done I think we are pretty close to ready for a core merge

**Comment by briis** [comment]
Thanks a lot Nick.
Shouldn't we move the the new ProtectApiClient also before the core integration? I don't understand all that has been done, but it looks smart.

When we get to that, I do need your help with the migration of the Websocket setup, as this is completely different from what you made in `data.py`.

**Comment by bdraco** [comment]
> Shouldn't we move the the new ProtectApiClient also before the core integration? I don't understand all that has been done, but it looks smart.

Yes we should.  I think that is the last step though since it would be good to get all the cleanups done first.  I have a few more PRs after this one.

**Comment by AngellusMortis** [comment]
I was able to successfully add the UFP integration and reconfigure it. It looks like that is where the majority of the changes were. Anything in particular you want me to test?

**Review by AngellusMortis — APPROVED** [review]

**Comment by bdraco** [comment]
> I was able to successfully add the UFP integration and reconfigure it. It looks like that is where the majority of the changes were. Anything in particular you want me to test?

This one likely blows up or it doesn't. Loading enough is probably enough testing.

Thanks 👍

**Pull request merged**
