### PR TITLE
Adds blueprints for automations

### PR DESCRIPTION
**Pull request by AngellusMortis**
I turned my existing automations into blueprints to make it easier for people to make their automations!

### Requirements

* You much have a valid HTTPS external URL (must have valid cert and the `/api/camera_proxy` and `/api/webhook` paths *must* be accessible.
* If you want to test HTML5 push notification (desktop Web browser / PWA notifications), you _must_ have Push Notifications configured: 
image
* If you want to test the mobile app push notifications, you _must_ have the HA Companion app installed on Android or iOS.

##### Motion Only

[Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbriis%2Funifiprotect%2Fblueprints%2Fblueprints%2Fautomation%2Funifiprotect%2Fpush_notification_motion_event.yaml)

##### Smart Detections Only

[Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbriis%2Funifiprotect%2Fblueprints%2Fblueprints%2Fautomation%2Funifiprotect%2Fpush_notification_smart_event.yaml)

* `push_notification_motion_event.yaml` / `push_notification_smart_event.yaml`: Two separate blueprints to do either Motion or Smart Detections Notifications. Includes current snapshot from camera and actionable notifications to open camera and silence notifications for that camera for a period of time.

#### Doorbell Notifications

[Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbriis%2Funifiprotect%2Fblueprints%2Fblueprints%2Fautomation%2Funifiprotect%2Fpush_notification_doorbell_event.yaml)

* `doorbell_event.yaml`: All-in-one blueprint to do Doorbell Notifications. Includes current snapshot from camera and actionable notifications to open camera, silence notifications for that camera for a period of time and unlock a `lock` entity.

### CODE REVIEW

**Comment by AngellusMortis** [comment]
@briis or @bdraco if you guys want to test these out. If you have an iOS device, that would be great since I only have Android.

**Comment by AngellusMortis** [comment]
As far as I can tell, the HTML5 Push notifications do _not_ work on a Mac. They may only work on Windows.

**Comment by AngellusMortis** [comment]
Added a cooldown setting for all of them as well as the motion/smart detection automations.

**Comment by AngellusMortis** [comment]
There also does not seem to be official way for integrations to provide blueprints as far as I can find. So, for now I think putting them in the root folder `blueprints` is good enough for now. After merge into core, We can either keep using this repo or make another one just for UFP blueprints. Or switch to using Gists like a lot of other people do.

**Comment by briis** [comment]
I have IOS devices, so just setup the Doorbell Image notification. Must wait for the Wife to be awake before playing with the Doorbell. Will report back.

**Comment by AngellusMortis** [comment]
I just found this awesome frigate blueprint: https://community.home-assistant.io/t/frigate-mobile-app-notifications/311091

So, I am going to rework these ones to update with everything I can learn from that one.

**Comment by AngellusMortis** [comment]
Okay. I added the updated blueprints. I was able to combine them all down into 2 based on the awesome things I learned from the Frigate ones. I am also more confident in iOS working properly as well since I got some great examples from there. 

@briis if you can test them on any of your devices if you want, that would be awesome. I am also going to go post them on the forums as well.

**Comment by briis** [comment]
Doorbell Motion Blueprint observations:
1. Notification Target (Mobile App) field: It was not obvious to me that I should only add the text after `notify.` , so I did not get any push on my phone. Not an error, just a UI observation.
2. Notification Target (HTML5 Push) field: This is prefilled with `push_notification`, and makes the script fail for me as I do not have this setup in my system. If I blank it out, it just comes back again when reopening the automation. Error message below. If you also look in the log it references a Camera that does not exist, as the stream type is not appended. It should be `camera.kamera_doerklokke_high` and not `camera.kamera_doerklokke`
3. Base Image URL field: Also here not obvious what to enter. I have tried with the nabu casa url and leaving it blank but I never get an image

I am not done testing, but these are initial findings on this Blueprint

```log
2021-12-05 11:58:23 ERROR (MainThread) [homeassistant.components.automation.unifi_protect_doorbell_notifications] UniFi Protect Doorbell Notifications: Error executing script. Service not found for call_service at pos 3: Unable to find service notify.push_notification
2021-12-05 11:58:23 ERROR (MainThread) [homeassistant.components.automation.unifi_protect_doorbell_notifications] Error while executing automation automation.unifi_protect_doorbell_notifications: Unable to find service notify.push_notification
2021-12-05 11:58:25 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities camera.kamera_doerklokke
2021-12-05 11:58:26 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities camera.kamera_doerklokke
2021-12-05 12:03:54 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities camera.kamera_doerklokke
````

**Comment by AngellusMortis** [comment]
Great feedback.

> Notification Target (Mobile App) field: It was not obvious to me that I should only add the text after notify. , so I did not get any push on my phone. Not an error, just a UI observation.

Yeah, there is no way to target services. I tried. I will give another look at the help texts and see if I can make it clearer

> Notification Target (HTML5 Push) field: This is prefilled with push_notification, and makes the script fail for me as I do not have this setup in my system. 

Did not know `push_notification` was just not there out of the box. I will have to rethink the input.

> It should be camera.kamera_doerklokke_high and not camera.kamera_doerklokke

It _should_ be pulling the first camera entity off of the device automatically. Do you have orphaned camera entities in the UI?

> It should be camera.kamera_doerklokke_high and not camera.kamera_doerklokke

I have never used Nabu Casa, but from my understanding of how it works, that _is_ what you should be using. However, if it is pulling the incorrect camera entity, it would never get the correct image URL.

Can you enable the "Debug" flag and give me the persistent notification that appears with the dump of the variables? Feel free to blur any of them out of just copy/paste and then star out anything you do not want to post publicly or DM it to me on the forums. You can also manually trigger it as well.

**Comment by AngellusMortis** [comment]
Also, great tip for debugging the notifications, you can go to Developers Tools -> Services and find the notify service that specifically targets _only_ your mobile phone so you are not spamming notifications to everyone!

**Comment by briis** [comment]
The Wife is back now, so it will have to wait until tomorrow with more testing as she gets very annoyed when keep pressing the doorbell :)
Will send you some more data.

I can however test the image URL stuuf with the other Blueprint. I might not get time tonight as we get visitors.

**Comment by AngellusMortis** [comment]
You can use "Run Actions" button to manually test without the event. And you can update the notify target to just your phone. That is how I was doing it without annoying the others in the house.

image

**Comment by AngellusMortis** [comment]
I added toggles for mobile/HTML5 notifications so you can send one or the other (or both). Also updated some of the help texts and added a state check for pulling the camera entity to make sure it is online.

**Comment by briis** [comment]
Oh yes, forgot about the RUN ACTIONS. (I am a Node Red user myself)

**Comment by AngellusMortis** [comment]
> (I am a Node Red user myself)

I am too. haha. It took me quite some time to convert my NodeRed automations to HA ones.

**Comment by briis** [comment]
A few more observations with the updated version of the Doorbell Blueprint:

- With the changes you made, and by entering my nabu casa url in the Base Image URL, it now work. I get the notification with an image - GREAT.
- Would be great if there was an option to change the Message and get the time in a different format. (I think you have to be American or British to still use AM/PM - the rest of the world moved on)

**Comment by briis** [comment]
And the message seems to have the timestamp hard coded in to it. I always get 8.57AM and right now it is 2PM here in Denmark.

**Comment by briis** [comment]
Testing the Motion/Smart Detection:
- Notification Channel is default Doorbell. Should be something else. Camera Motion or similar.
- Message: Time is correct, except for the AM/PM format. But also here it should be customizable.

> And the message seems to have the timestamp hard coded in to it. I always get 8.57AM and right now it is 2PM here in Denmark.

Forget this comment, when I actually pressed the Doorbell button, the correct time came up.

So to sum up, if you fix the Notification Channel in the Motion Blueprint and make it possible to customize the message text, we are good to go. And btw. this is so cool, that it is now so easy to get this done. For reference here is what I put in the Base Image URL and that works: `https://YOUR_NABUCASA_ID.ui.nabu.casa`

**Comment by AngellusMortis** [comment]
> Message and get the time in a different format.

That requires getting into time format strings. I can add it, but I do not know if most users will bother. AM/PM seems like a format everyone can understand.

> And the message seems to have the timestamp hard coded into it. 

That is the result of you manually using Run Actions. It actually uses the "last changed" time on the entity itself. So, if you are using the manual test, it gives the same time every time because it has not actually changed. Adding in the last changed time was how I dealt with notifications that got horribly delayed so you can tell when the notification was actually for.

> Notification Channel is default Doorbell. Should be something else. Camera Motion or similar.

Copy and paste error from updating the template. I will fix that.

**Comment by briis** [comment]
Have you figured out how to update a Blueprint? I delete the old ones and add them again, but there must be a smarter way?

**Comment by AngellusMortis** [comment]
I have been editing directly on my instance, so I have not been doing that. But I _think_ the expected way is to use the same path and everything for the blueprint when you import them again. The official recommendation from HA is to make sure blueprints are always backwards compatible.

> When a user imports a blueprint, Home Assistant stores the URL from which it was imported. This will allow Home Assistant in the future to update blueprints by looking at updated blueprint code in the forum topic.
>
> It is therefore important that your blueprints remain backwards compatible. Do not change selectors or input names. If you add new selectors, make sure they have a default value so that existing automations keep working when the blueprint is updated.

https://community.home-assistant.io/t/about-blueprints/253788

**Comment by briis** [comment]
These both work perfectly now, and can be released.👍🏻

One potential future change: With the new Thumbnail feature, why not attach the Thumbnail instead of a snapshot. I still have some timing issues with the image, not containing the person that has moved in front of the Camera, and that might not be the case with the Protect Thumbnail

**Comment by briis** [comment]
Why not put the links in a topic in the Discussion Area, and then Pin that to the Top.

**Comment by AngellusMortis** [comment]
> These both work perfectly now, and can be released.👍🏻

I am actually going to put it back into draft. I want to wait until we do 0.11-beta3 so I can update them with the updated and separated motion/smart detection sensors.

> One potential future change: With the new Thumbnail feature, why not attach the Thumbnail instead of a snapshot.

That is the plan.

**Comment by AngellusMortis** [comment]
> > One potential future change: With the new Thumbnail feature, why not attach the Thumbnail instead of a snapshot.
> 
> That is the plan. I was also thinking of adding TTS as well (for the doorbell, not the motion/smart).

It looks like this is not going to be possible. After more testing and looking into how thumbnails work, they do not actually generate until after the event ends. So, you can only use thumbnail if you can ensure all events are less than ~10 seconds or some other reasonable about of time.

**Comment by AngellusMortis** [comment]
Talkback is still acting up on my doorbell, so I am going to call it done for this PR for now.

**Comment by briis** [comment]
> It looks like this is not going to be possible.

All my testing in the past also showed that the Thumbnail was not generated before the end of the event, but I thought you might have found a workaround 😁 It will just have to be the Camera Picture then, and hopefully the latency can be minimized in future HA versions.

**Comment by AngellusMortis** [comment]
It is not a latency issue. If you look at the view for the thumbnails, they hit UniFi Protect in real time. I was testing it this morning and Protect would not respond with the thumbnail until after the WS message for the event ending occurred (i.e. the sensor turned off).

**Comment by briis** [comment]
The latency I referred to was the stream delay in HA, which then results in a snapshot that is not containing the smart object, as there is a delay of 5-10 seconds.

But interesting that UniFi has the Thumbnail in realtime, so it must be there somewhere, or what?

**Comment by AngellusMortis** [comment]
So the snapshots were never actually delayed. There is no actual notable delay in the stream. So when you use entity_picture or call snapshot manually, it in turns calls the get_camera_snapshot and return a real live image.

There was actually another issue where someone was noticing the feeds had _less_ latency with streaming turned off (but obviously were only like 1 frame per second lol).

**Comment by AngellusMortis** [comment]
> But interesting that UniFi has the Thumbnail in realtime, so it must be there somewhere, or what?

I thought that too, UT the API is not giving me one. So maybe they are not using the real even thumbs? I will need to do more testing for that myself.

**Comment by briis** [comment]
Ok. I often don't manage to capture myself when walking in front of my Camera, when Smart Detect is the criteria.

**Comment by AngellusMortis** [comment]
Just got done doing more testing with Protect:

* WebUI: actually, uses a camera snapshot for the "event thumb" in the feeds for recent events. I noticed the images were never properly zoomed in me or anything for events that happened recently (last ~1 hour)
* Android push: uses camera snapshot.
* Email: uses event thumbnail (but I did not get them until much later after the push notifications)

So, I do not think Protect has access to anything that is not being exposed already via the UI.

**Comment by briis** [comment]
Thanks for testing this out.

**Comment by AngellusMortis** [comment]
I was seeing a lot of performance issues after upgrading to 2021.12 and figured out it was because of these automations. The plain `event: state_changed` was causing way too much CPU. To fix it, I unfortunately had to get rid of the fancy Target selector and fall back to only a single entity. That means each instance of the automation can only handle a single camera and you need multiple ones to get all of your cameras. 

I also had to split motion / smart back into two separate blueprints as well since you cannot template the `entity_id` value for state triggers.

**Comment by briis** [comment]
I have now tested all Blueprints, and they work extremely well. So with my eyes these are ready to merge.

**Pull request merged**
