### PR TITLE
fix(g4doorbell/chime_duration): Add missing SCHEMA

### PR DESCRIPTION
**Pull request by mohlek**

### CODE REVIEW

**Comment by mohlek** [comment]
Sry missed that.
Still not tested. Need to prepare test environment first

**Comment by briis** [comment]
No worries, I had already made this change, and I will test it in a minute.
There was also something missing in camera.py, which I have fixed.

**Comment by mohlek** [comment]
looking forward to see this being released.
Thanks for your work.

**Comment by briis** [comment]
I am more or less done now. I decided to make the step interval 100 instead of 1, on the duration. 
But just download the changed files, overwrite what you have in the custom_components directory and you should be up and running now.

Thanks for your help.

**Comment by mohlek** [comment]
works as intended. Thanks

**Pull request merged**
