### PR TITLE
Additional cleanups

### PR DESCRIPTION
**Pull request by bdraco**
- Reduce `select` code
- pylint error fixes (`id` not a valid name)
- Reduce duplicate code in `__init__`
- Move code that cannot fail outside of `try`
- Add missing `configuration_url` to main device

### CODE REVIEW

**Comment by AngellusMortis** [comment]
Looks like the select for the doorbell text is busted. Relevant logs:

```
2021-11-23 19:58:27 ERROR (MainThread) [homeassistant.components.select] Error adding entities for domain select with platform unifiprotect
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/components/select/__init__.py", line 93, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/unifiprotect/select.py", line 238, in current_option
    return self._unifi_to_hass_options[unifi_value]
KeyError: 'Welcome'
```

**Comment by bdraco** [comment]
I think I've got it.  

I don't have a doorbell on my production setup so its a bit of a guess

**Comment by bdraco** [comment]
Actually multiple values are supported so we can't have a 1:1 dict :(

**Comment by AngellusMortis** [comment]
If it helps, the way they are modeled in UFP are:

```
[
    {
        "type": "CUSTOM_MESSAGE",
        "text": str
    },
    {
        "type": "LEAVE_PACKAGE_AT_DOOR",
        "text": "LEAVE PACKAGE AT DOOR"
    },
    {
        "type": "DO_NOT_DISTURB",
        "text": "DO NOT DISTURB"
    }
]
```

**Comment by bdraco** [comment]
I think the last push will fix it.  If not I'll get the test doorbell out and hook it up

**Comment by AngellusMortis** [comment]
All of my selects are broken now. 

```
2021-11-23 20:18:44 ERROR (MainThread) [homeassistant.components.select] Error while setting up unifiprotect platform for select
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/unifiprotect/select.py", line 184, in async_setup_entry
    UnifiProtectSelects(
  File "/config/custom_components/unifiprotect/select.py", line 224, in __init__
    self._attr_options = [item["name"] for item in options]
  File "/config/custom_components/unifiprotect/select.py", line 224, in <listcomp>
    self._attr_options = [item["name"] for item in options]
TypeError: string indices must be integers
```

**Comment by bdraco** [comment]
I updated the debug log to show the options.  Can you check to see which one is missing the `name`?

```
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for 8th st East with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Garage by Power with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Garage with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for David Office with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Alexander Facing South with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Corner with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for 8th Mid with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Northeast corner with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Driveway East with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Pool with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for North Side yard with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for 8th st West with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Gate with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Alexander Facing North with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Driveway West with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Backyard by Glass Doors with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Recording Mode for Back Door with options [{'id': 'always', 'name': 'Always'}, {'id': 'never', 'name': 'Never'}, {'id': 'detections', 'name': 'Detections'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for 8th st East with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Garage by Power with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Garage with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for David Office with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Alexander Facing South with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Corner with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for 8th Mid with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Northeast corner with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Driveway East with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Pool with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for North Side yard with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for 8th st West with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Gate with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Alexander Facing North with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Driveway West with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Backyard by Glass Doors with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
2021-11-23 14:32:35 DEBUG (MainThread) [custom_components.unifiprotect.select] Adding select entity Infrared for Back Door with options [{'id': 'auto', 'name': 'Auto'}, {'id': 'on', 'name': 'Always Enable'}, {'id': 'autoFilterOnly', 'name': "Auto (Filter Only, no LED's)"}, {'id': 'off', 'name': 'Always Disable'}]
```

**Comment by AngellusMortis** [comment]
Looks good now. Only issue I see still if the streaming one I mentioned to you. I will have to likely debug that more tomorrow myself to see what is causing it.

**Review by AngellusMortis — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks.  I'll work down the list a bit more later today if I have another free block.  If I see any streaming issues I'll report back

**Pull request merged**
