### PR TITLE
Adds TTS for doorbell notification

### PR DESCRIPTION
**Pull request by AngellusMortis**
Since I got TTS messages 100% fixed for 0.11.1, here are TTS messages for the Doorbell notification blueprint.

### CODE REVIEW

**Comment by AngellusMortis** [comment]
@briis if you want to check out the TTS part. They work great on my camera.

**Comment by briis** [comment]
I will give it a try later today.

**Comment by briis** [comment]
I have tried to get my Cameras to say something but nothing happens (They have been rebooted). I am not getting any errors but I see the below in the log file. Sound is set to 90%, so I should hear something. What else could I try?

```log
2021-12-19 07:40:22 DEBUG (MainThread) [custom_components.unifiprotect.media_player] Playing Media http://172.17.0.6:9123/api/tts_proxy/640ab2bae07bedc4c163f679a746f7ab7fb5d1fa_en_-_google_translate.mp3 for Kamera Koekken Speaker
2021-12-19 07:40:22 DEBUG (MainThread) [pyunifiprotect.stream] ffmpeg: /usr/bin/ffmpeg -loglevel info -hide_banner -i http://172.17.0.6:9123/api/tts_proxy/640ab2bae07bedc4c163f679a746f7ab7fb5d1fa_en_-_google_translate.mp3 -vn -acodec aac -ac 1 -ar 22050 -b:a 48000 -map 0:a -f adts udp://192.168.1.209:7004
2021-12-19 07:40:22 DEBUG (MainThread) [pyunifiprotect.data.devices] ffmpeg stdout:

2021-12-19 07:40:22 DEBUG (MainThread) [pyunifiprotect.data.devices] ffmpeg stderr:
[mp3 @ 0x559c04fa2f00] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'http://172.17.0.6:9123/api/tts_proxy/46b65ae52b8cc0322787c9f7b929407e8643f451_en_-_google_translate.mp3':
  Metadata:
    Text            : en
  Duration: 00:00:01.78, start: 0.000000, bitrate: 36 kb/s
    Stream #0:0: Audio: mp3, 24000 Hz, mono, fltp, 32 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> aac (native))
Press [q] to stop, [?] for help
Output #0, adts, to 'udp://192.168.1.209:7004':
  Metadata:
    Text            : en
    encoder         : Lavf58.45.100
    Stream #0:0: Audio: aac (LC), 22050 Hz, mono, fltp, 48 kb/s
    Metadata:
      encoder         : Lavc58.91.100 aac
size=      11kB time=00:00:01.81 bitrate=  48.4kbits/s speed=66.8x
video:0kB audio:10kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.624672%
[aac @ 0x559c04fbe6c0] Qavg: 8528.154
[mp3 @ 0x55c5466d9f00] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'http://172.17.0.6:9123/api/tts_proxy/640ab2bae07bedc4c163f679a746f7ab7fb5d1fa_en_-_google_translate.mp3':
  Metadata:
    Text            : en
  Duration: 00:00:01.01, start: 0.000000, bitrate: 40 kb/s
    Stream #0:0: Audio: mp3, 24000 Hz, mono, fltp, 32 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> aac (native))
Press [q] to stop, [?] for help
Output #0, adts, to 'udp://192.168.1.209:7004':
  Metadata:
    Text            : en
    encoder         : Lavf58.45.100
    Stream #0:0: Audio: aac (LC), 22050 Hz, mono, fltp, 48 kb/s
    Metadata:
      encoder         : Lavc58.91.100 aac
size=       9kB time=00:00:01.02 bitrate=  69.6kbits/s speed=95.5x
video:0kB audio:9kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.843793%
[aac @ 0x55c5466fc100] Qavg: 19396.486
[mp3 @ 0x562e62fa2f00] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'http://172.17.0.6:9123/api/tts_proxy/640ab2bae07bedc4c163f679a746f7ab7fb5d1fa_en_-_google_translate.mp3':
  Metadata:
    Text            : en
  Duration: 00:00:01.01, start: 0.000000, bitrate: 40 kb/s
    Stream #0:0: Audio: mp3, 24000 Hz, mono, fltp, 32 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> aac (native))
Press [q] to stop, [?] for help
Output #0, adts, to 'udp://192.168.1.209:7004':
  Metadata:
    Text            : en
    encoder         : Lavf58.45.100
    Stream #0:0: Audio: aac (LC), 22050 Hz, mono, fltp, 48 kb/s
    Metadata:
      encoder         : Lavc58.91.100 aac
size=       9kB time=00:00:01.02 bitrate=  69.6kbits/s speed=92.6x
video:0kB audio:9kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.843793%
[aac @ 0x562e62fc5100] Qavg: 19396.486
````

**Comment by briis** [comment]
I see you use Google text to speach - I normally don't use that, but I use `tts.cloud_say` service, which I find better than Google, and then I don't have to send stuff to Google for translating. But that service requires that Nabu Casa is used, which I don't think everybody has.
Anyway, I tried to use that service with the cameras, and it does not work for me either.

**Comment by AngellusMortis** [comment]
I used the Google one in the main repo for development because it is "easiest" one to set up. At home I actually use the [Microsoft one](https://www.home-assistant.io/integrations/microsoft/). It is much harder to setup (requires a Microsoft/Azure account and you have to make an Azure Speech Resource), but it is the best one that I have found. And the widest array of choices. It even has a Danish one:

image

**Comment by AngellusMortis** [comment]
Let me setup cloud_say and test it out, but nothing in your output looks wrong. You are on 0.11.1 correct? Can you use to the media to send a TTS message to the doorbell (or any speaker camera) ad-hoc?

**Comment by AngellusMortis** [comment]
cloud_say is definitely working for me. I just tested it with both my G4 Dome and G4 Doorbell.

(also as a note, the cloud_say voice sounds like it is the microsoft_say one, I know Home Assistant is sponsored by Microsoft, so I wonder if it is)

**Comment by briis** [comment]
OK, I am officially an idiot🥴
I tested from Visual Studio, and try to use the Cloud Say - But that does not work, as it is not setup in the Dev environment.
Just tried it on my production system that runs V0.11.1 and it works fine. Sorry for the confusion.

So please merge.

**Pull request merged**
