### PR TITLE
Update doorbell device class

### PR DESCRIPTION
**Pull request by bdraco**
I finally picked up the Unifi doorbell and noticed that HomeKit didn't link
the button automatically because the device class was not a valid one.

Home Assistant is using device class occupancy for
doorbells:

https://developers.home-assistant.io/docs/core/entity/binary-sensor

### CODE REVIEW

**Comment by bdraco** [comment]
I wasn't able to finish testing before I had to leave.  I'll leave this as a draft until I have some more time to test

**Comment by bdraco** [comment]
```
2020-11-01 23:49:22 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Action Frame: {'action': 'update', 'newUpdateId': '7842b7e3-cc1f-46b0-9ace-861b3c22ce0f', 'modelKey': 'nvr', 'id': '5e539ed301e57003870003e9'}
2020-11-01 23:49:22 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Action Frame: {'action': 'update', 'newUpdateId': 'bd7a0f96-b7ba-462e-902b-19bfdbc524a4', 'modelKey': 'camera', 'id': '5f9f43f102f7d90387004da5'}
2020-11-01 23:49:22 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'lastMotion': 1604274691559}
2020-11-01 23:49:22 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Last Motion Set: 5f9f43f102f7d90387004da5 at 1604274691559
2020-11-01 23:49:22 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Websocket triggered update but there was no event for: 5f9f43f102f7d90387004da5
--
2020-11-01 23:49:23 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'isMotionDetected': False}
2020-11-01 23:49:23 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Action Frame: {'action': 'update', 'newUpdateId': 'a2dea53a-66e3-4cb2-a338-54c69193eedf', 'modelKey': 'camera', 'id': '5f9f43f102f7d90387004da5'}
2020-11-01 23:49:23 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'lastMotion': 1604274692236}
2020-11-01 23:49:23 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Last Motion Set: 5f9f43f102f7d90387004da5 at 1604274692236
2020-11-01 23:49:23 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Websocket triggered update but there was no event for: 5f9f43f102f7d90387004da5
--
2020-11-01 23:49:25 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Skipping update since websocket is active
2020-11-01 23:49:25 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Action Frame: {'action': 'update', 'newUpdateId': '65b9ac96-dea1-459d-8da3-379ed34a53d6', 'modelKey': 'camera', 'id': '5e539ed503617003870003ed'}
2020-11-01 23:49:25 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'lastMotion': 1604274695462}
2020-11-01 23:49:25 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Last Motion Set: 5e539ed503617003870003ed at 1604274695462
2020-11-01 23:49:25 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Websocket triggered update but there was no event for: 5e539ed503617003870003ed
--
2020-11-01 23:49:28 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'lastSeen': 1604274698086}
2020-11-01 23:49:28 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Action Frame: {'action': 'update', 'newUpdateId': '16efac71-2e01-4b66-836d-3fd2b80f0a4e', 'modelKey': 'camera', 'id': '5e539ed503617003870003ed'}
2020-11-01 23:49:28 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'lastSeen': 1604274698089, 'lastMotion': 1604274697801}
2020-11-01 23:49:28 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Last Motion Set: 5e539ed503617003870003ed at 1604274697801
2020-11-01 23:49:28 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Websocket triggered update but there was no event for: 5e539ed503617003870003ed
--
2020-11-01 23:49:29 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Skipping update since websocket is active
2020-11-01 23:49:30 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Action Frame: {'action': 'update', 'newUpdateId': 'ca252143-cbbe-48b3-8d49-9268e378bb2c', 'modelKey': 'camera', 'id': '5e539ed503617003870003ed'}
2020-11-01 23:49:30 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'lastMotion': 1604274700165}
2020-11-01 23:49:30 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Last Motion Set: 5e539ed503617003870003ed at 1604274700165
2020-11-01 23:49:30 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Websocket triggered update but there was no event for: 5e539ed503617003870003ed
--
2020-11-01 23:49:35 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Skipping update since websocket is active
2020-11-01 23:49:35 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Action Frame: {'action': 'update', 'newUpdateId': '5d0c8e2f-fa8e-4717-a0c6-8699184bae0e', 'modelKey': 'camera', 'id': '5e539ed503617003870003ed'}
2020-11-01 23:49:35 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'lastMotion': 1604274704846}
2020-11-01 23:49:35 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Last Motion Set: 5e539ed503617003870003ed at 1604274704846
2020-11-01 23:49:36 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Websocket triggered update but there was no event for: 5e539ed503617003870003ed
--
2020-11-01 23:49:36 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'isMotionDetected': False}
2020-11-01 23:49:36 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Action Frame: {'action': 'update', 'newUpdateId': 'c04a65f0-6ec0-4b08-ab6b-4952e322d6cf', 'modelKey': 'camera', 'id': '5e539ed503617003870003ed'}
2020-11-01 23:49:36 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'lastMotion': 1604274704944}
2020-11-01 23:49:36 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Last Motion Set: 5e539ed503617003870003ed at 1604274704944
2020-11-01 23:49:36 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Websocket triggered update but there was no event for: 5e539ed503617003870003ed
```


```
2020-11-01 23:49:03 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Action Frame: {'action': 'update', 'newUpdateId': '1cd890a2-6191-4a51-9ebc-87bce6512f70', 'modelKey': 'camera', 'id': '5f9f43f102f7d90387004da5'}
2020-11-01 23:49:03 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Data Frame: {'lastRing': 1604274673380}
2020-11-01 23:49:03 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Last Ring Set: 5f9f43f102f7d90387004da5 at 1604274673380
```
Looks like events trail behind too long for doorbells

**Comment by bdraco** [comment]
It looks like the events api can be seconds or even minutes behind.  I think I need to refactor the websocket code a bit since its much faster at delivering events.

**Comment by bdraco** [comment]
Three problems:

1. If the system is loaded, we miss events because the time has already passed.
2. If the doorbell is rung at the same time as motion, we don't see the ring event because the motion event obscures it.
3. If the hass clock and unifi clock are out of sync, we see the wrong events.

**Comment by bdraco** [comment]
The other issues are addre

> Three problems:
> 
> 1. If the system is loaded, we miss events because the time has already passed.
> 2. If the doorbell is rung at the same time as motion, we don't see the ring event because the motion event obscures it.
> 3. If the hass clock and unifi clock are out of sync, we see the wrong events.

Fixed in https://github.com/briis/pyunifiprotect/pull/10

**Comment by briis** [comment]
Thank you.

**Pull request merged**
